spring:
  application:
    name: zuul
    
server:
  port: 8769    
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: ribbon
    api-b:
      path: /api-b/**
      serviceId: eureka-client